const alphabet = "abcdefghijklmnopqrstuvwxyz";
const numbers = "0123456789";
const symbols = "~!@#$%^&*()_-+={}[]|\\'\"<>:;,./?";

export const allowedKeys = [...alphabet, ...alphabet.toUpperCase(), ...numbers, ...symbols, " "];

const words = [
  "the",
  "of",
  "to",
  "and",
  "a",
  "is",
  "you",
  "that",
  "he",
  "was",
  "for",
  "on",
  "are",
  "with",
  "as",
  "I",
  "his",
  "they",
  "be",
  "at",
  "one",
  "have",
  "this",
  "from",
  "or",
  "had",
  "by",
  "hot",
  "word",
  "but",
  "what",
  "some",
  "we",
  "can",
  "out",
  "other",
  "it",
  "were",
  "all",
  "there",
  "when",
  "up",
  "use",
  "your",
  "how",
  "said",
  "an",
  "each",
  "she",
  "which",
  "do",
  'Success is a journey, not a destination.',
  'The future belongs to those who believe in their dreams.',
  'Wisdom is knowing the right path to take.',
  'A mind that is stretched by new experiences can never go back.',
  'Every problem has a gift for you in its hands.',
  'The greatest glory in living lies not in never falling, but in rising every time we fall.',
  'Life is what happens when you&apos;re busy making other plans.',
  'It is not the length of life, but depth of life that matters.',
  'Happiness is not something ready-made; it comes from your own actions.',
  'The only limit to our realization of tomorrow will be our doubts of today.',
  'It is during our darkest moments that we must focus to see the light.',
  'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.',
  'Our lives begin to end the day we become silent about things that matter.',
  'The only way to do great work is to love what you do.',
  'Your time is limited, so don&apos;t waste it living someone else&apos;s life.',
  'Success usually comes to those who are too busy to be looking for it.',
  'The purpose of our lives is to be happy.',
  'In the end, we will remember not the words of our enemies, but the silence of our friends.',
  'Believe you can and you&apos;re halfway there.',
  'What lies behind us and what lies before us are tiny matters compared to what lies within us.',
  'Act as if what you do makes a difference. It does.',
  'The best way to predict the future is to create it.',
  'Life is either a daring adventure or nothing at all.',
  'You are never too old to set another goal or to dream a new dream.',
  'Change your thoughts and you change your world.',
  'Success is not final, failure is not fatal: It is the courage to continue that counts.',
  'To live is the rarest thing in the world. Most people exist, that is all.',
  'Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.',
  'What we think, we become.',
  'The only way to achieve the impossible is to believe it is possible.',
  'We cannot solve our problems with the same thinking we used when we created them.',
  'Every day may not be good, but there&apos;s something good in every day.',
  'The best revenge is massive success.',
  'Sometimes you will never know the value of a moment until it becomes a memory.',
  'It does not matter how slowly you go as long as you do not stop.',
  'A person who never made a mistake never tried anything new.',
  'Everything you can imagine is real.',
  'Life is really simple, but we insist on making it complicated.',
  'Dream big and dare to fail.',
  'What we fear doing most is usually what we most need to do.',
  'Success is walking from failure to failure with no loss of enthusiasm.',
  'Your life does not get better by chance, it gets better by change.',
  'Everything has beauty, but not everyone sees it.',
  'Believe in yourself and all that you are.',
  'The journey of a thousand miles begins with one step.',
  'The only impossible journey is the one you never begin.',
  'It always seems impossible until it is done.',
  'You miss 100% of the shots you don&apos;t take.',
  'Be the change that you wish to see in the world.',
  'The mind is everything. What you think you become.',
  'Success is how high you bounce when you hit bottom.',
  'Do not wait to strike till the iron is hot, but make it hot by striking.',
  'You cannot swim for new horizons until you have courage to lose sight of the shore.',
  'The road to success and the road to failure are almost exactly the same.',
  'It is not enough to win a war; it is more important to organize the peace.',
  'Perfection is not attainable, but if we chase perfection we can catch excellence.',
  'In order to succeed, we must first believe that we can.',
  'Life isn&apos;t about finding yourself. Life is about creating yourself.',
  'Do what you can, with what you have, where you are.',
  'Success is not how high you have climbed, but how you make a positive difference to the world.',
  'You are braver than you believe, stronger than you seem, and smarter than you think.',
  'Do not go where the path may lead, go instead where there is no path and leave a trail.',
  'Life is short, and it is up to you to make it sweet.',
  'To live is the rarest thing in the world. Most people exist, that is all.',
  'The purpose of our lives is to be happy.',
  'If you cannot do great things, do small things in a great way.',
  'Live as if you were to die tomorrow. Learn as if you were to live forever.',
  'We are what we repeatedly do. Excellence, then, is not an act, but a habit.',
  'To succeed in life, you need three things: a wishbone, a backbone, and a funny bone.',
  'Success is the sum of small efforts, repeated day in and day out.',
  'Strive not to be a success, but rather to be of value.',
  'Life isn&apos;t about waiting for the storm to pass; it&apos;s about learning to dance in the rain.',
  'The best way out is always through.',
  'When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.',
  'If you want to lift yourself up, lift up someone else.',
  'There are no limits to what you can accomplish, except the limits you place on your own thinking.',
  'You have within you right now, everything you need to deal with whatever the world can throw at you.',
  'Keep your face always toward the sunshine—and shadows will fall behind you.',
  'Opportunities don&apos;t happen, you create them.',
  'Success is the ability to go from one failure to another with no loss of enthusiasm.',
  'The greatest discovery of all time is that a person can change his future by merely changing his attitude.',
  'If you can dream it, you can achieve it.',
  'You only live once, but if you do it right, once is enough.',
  'Challenges are what make life interesting, and overcoming them is what makes life meaningful.',
  'We become what we think about.',
  'Act as if what you do makes a difference. It does.',
  'A goal without a plan is just a wish.',
  'Success isn&apos;t just about what you accomplish in your life, it&apos;s about what you inspire others to do.',
  "their",
  "time",
  "if",
  "will be the same",
  "way",
  "about",
  "many times",
  "then",
  "them",
  "write",
  "would",
  "like us",
  "so",
  "these",
  "her",
  "in",
  "long",
  "make this possible",
  "thing",
  "see",
  "him",
  "two",
  "has",
  "look",
  "more",
  "day",
  "could be in our hand",
  "go",
  "come",
  "did",
  "number",
  "sound",
  "no",
  "most",
  "people",
  "my",
  "over",
  "know her reality",
  "water",
  "than",
  "call",
  "first",
  "who",
  "may be in the next life",
  "down",
  "side",
  "been",
  "now",
  "find",
  "any",
  "new",
  "work",
  "part",
  "take",
  "get",
  "place of peace",
  "made",
  "live",
  "where",
  "after",
  "back",
  "little",
  "only",
  "round",
  "man",
  "year",
  "came to my mind",
  "show",
  "every",
  "good",
  "me",
  "give her presence",
  "our",
  "under",
  "name",
  "very",
  "through",
  "just",
  "form",
  "sentence of death",
  "great",
  "think",
  "say",
  "help",
  "low",
  "line",
  "differ",
  "turn",
  "cause of panelty",
  "much",
  "mean",
  "before",
  "move",
  "right",
  "boy",
  "old",
  "too",
  "same as earlier",
  "tell",
  'The complexities of human emotions are profound.',
  'Navigating through life&apos;s uncertainties requires courage.',
  'Philosophical inquiries often lead to existential dilemmas.',
  'Understanding others begins with empathy and patience.',
  'The essence of creativity lies in breaking boundaries.',
  'In the face of adversity, resilience is paramount.',
  'Art has the power to transcend cultural barriers.',
  'Knowledge is a vast ocean, and curiosity is the vessel.',
  'Conversations can spark revolutions in thought.',
  'Exploring new ideas fosters intellectual growth.',
  'Diversity enriches our understanding of the world.',
  'Time is a relentless river that flows in one direction.',
  'The journey of self-discovery is often labyrinthine.',
  'Challenging the status quo can lead to innovation.',
  'Every decision we make shapes our destiny.',
  'Perception can be a deceptive lens through which we view reality.',
  'The intricacies of language can bridge or divide us.',
  'True happiness often lies in the pursuit of passions.',
  'Collaboration amplifies the impact of individual efforts.',
  'Inspiration can strike in the most unexpected moments.',
  'Finding balance amidst chaos is an art form.',
  'The quest for knowledge is a lifelong endeavor.',
  'History teaches us lessons that echo through time.',
  'A simple act of kindness can ignite hope.',
  'Embracing vulnerability is a sign of strength.',
  'The human spirit is capable of remarkable resilience.',
  'Chasing dreams requires unwavering determination.',
  'Innovation thrives in environments that encourage risk-taking.',
  'Understanding the past is crucial for shaping the future.',
  'Greatness often stems from humility and hard work.',
  'A moment of silence can speak volumes.',
  'Love can be both a sanctuary and a battleground.',
  'The tapestry of life is woven with diverse experiences.',
  'Leadership is about empowering others to shine.',
  'Cultivating patience is essential for personal growth.',
  'The impact of our words can resonate for a lifetime.',
  'Understanding the interconnectedness of all things is enlightening.',
  'Self-reflection is a powerful tool for growth.',
  'The beauty of nature often mirrors our innermost feelings.',
  'Every setback can serve as a setup for a comeback.',
  'Authenticity attracts genuine connections.',
  'Our perceptions shape our realities in profound ways.',
  'The silence of the night can bring clarity to the mind.',
  'Forgiveness liberates the soul from burdens.',
  'Cultivating gratitude enhances our overall well-being.',
  'The art of storytelling preserves cultures and histories.',
  'Time spent in nature can rejuvenate the spirit.',
  'Courage is not the absence of fear but the triumph over it.',
  'Each encounter holds the potential for meaningful change.',
  'Exploration is the heartbeat of human existence.',
  'Dreams are the seedlings of our realities.',
  'The quest for meaning often leads to unexpected paths.',
  'Adversity can forge character and resilience.',
  'The rhythm of life is often found in the moments of stillness.',
  "does",
  "set",
  "three",
  "want",
  "air",
  "well",
  "also",
  "play",
  "small",
  "end of the topic",
  "put",
  "home",
  "read",
  "hand",
  "port",
  "large",
  "spell",
  "add",
  "even",
  "land",
  "here",
  "must",
  "big Screen",
  "high",
  "such",
  "follow to your elders",
  "act",
  "why",
  "ask",
  "men",
  "change",
  "went",
  "light",
  "kind",
  "off",
  "need",
  "Always listen to your elders.",
  "Take decisive action.",
  "Why do we hesitate?",
  "Never hesitate to ask.",
  "The men worked diligently.",
  "Embrace change with open arms.",
  "He went on an adventure.",
  "The light illuminated the path.",
  "Show kindness to others.",
  "Turn off the lights when leaving.",
  "You need to take a break.",
  "Welcome to my house.",
  "Capture the perfect picture.",
  "Always try your best.",
  "Join us for the celebration.",
  "Lets try again, together.",
  "Every animal has its purpose.",
  "Point to the right direction.",
  "My mother is my inspiration.",
  "Explore the wonders of the world.",
  "house",
  "picture",
  "try",
  "us",
  "again",
  "animal",
  "point",
  "mother",
  "world",
  "near",
  "build",
  "self",
  "earth",
  "father",
  "head",
  "stand",
  "own",
  "page",
  "should",
  "country",
  "found",
  "answer",
  "school",
  "grow",
  "study",
  "still",
  "learn",
  "plant",
  "cover",
  "food",
  "sun",
  "four",
  "between",
  "state",
  "keep",
  "eye",
  "never",
  "last",
  "let",
  "thought",
  "city",
  "tree",
  "cross",
  "farm",
  "hard",
  "start",
  "might",
  "story",
  "saw",
  "far",
  "sea",
  "draw",
  "left",
  "late",
  "run",
  "don't",
  "while",
  "press",
  "close",
  "night",
  "real",
  "life",
  "few",
  "north",
  "open",
  "seem",
  "together",
  "next",
  "white",
  "children",
  "begin",
  "got",
  "walk",
  "example",
  "ease",
  "paper",
  "group",
  "always",
  "music",
  "those",
  "both",
  "mark",
  "often",
  "letter",
  "until",
  "mile",
  "river",
  "car",
  "feet",
  "care",
  "second",
  "book",
  "carry",
  "took",
  "science",
  "eat",
  "room",
  "friend",
  "began",
  "idea",
  "fish",
  "mountain",
  "stop",
  "once",
  "base",
  "hear",
  "horse",
  "cut",
  "sure",
  "watch",
  "color",
  "face",
  "wood",
  "main",
  "enough",
  "plain",
  "girl",
  "usual",
  "young",
  "ready",
  "above",
  "ever",
  "red",
  "list",
  "though",
  "feel",
  "talk",
  "bird",
  "soon",
  "body",
  "dog",
  "family",
  "direct",
  "pose",
  "leave",
  "song",
  "measure",
  "door",
  "product",
  "black",
  "short",
  "numeral",
  "class",
  "wind",
  "question",
  "happen",
  "complete",
  "ship",
  "area",
  "half",
  "rock",
  "order",
  "fire",
  "south",
  "problem",
  "piece",
  "told",
  "knew",
  "pass",
  "since",
  "top",
  "whole",
  "king",
  "space",
  "heard",
  "best",
  "hour",
  "better",
  "true",
  "during",
  "hundred",
  "five",
  "remember",
  "step",
  "early",
  "hold",
  "west",
  "ground",
  "interest",
  "reach",
  "fast",
  "verb",
  "sing",
  "listen",
  "six",
  "table",
  "travel",
  "less",
  "morning",
  "ten",
  "simple",
  "several",
  "vowel",
  "toward",
  "war",
  "lay",
  "against",
  "pattern",
  "slow",
  "center",
  "love",
  "person",
  "money",
  "serve",
  "appear",
  "road",
  "map",
  "rain",
  "rule",
  "govern",
  "pull",
  "cold",
  "notice",
  "voice",
  "unit",
  "power",
  "town",
  "fine",
  "certain",
  "fly",
  "fall",
  "lead",
  "cry",
  "dark",
  "machine",
  "note",
  "wait",
  "plan",
  "figure",
  "star",
  "box",
  "noun",
  "field",
  "rest",
  "correct",
  "able",
  "pound",
  "done",
  "beauty",
  "drive",
  "stood",
  "contain",
  "front",
  "teach",
  "week",
  "final",
  "gave",
  "green",
  "oh",
  "quick",
  "develop",
  "ocean",
  "warm",
  "free",
  "minute",
  "strong",
  "special",
  "mind",
  "behind",
  "clear",
  "tail",
  "produce",
  "fact",
  "street",
  "inch",
  "multiply",
  "nothing",
  "course",
  "stay",
  "wheel",
  "full",
  "force",
  "blue",
  "object",
  "decide",
  "surface",
  "deep",
  "moon",
  "island",
  "foot",
  "system",
  "busy",
  "test",
  "record",
  "boat",
  "common",
  "gold",
  "possible",
  "plane",
  "stead",
  "dry",
  "wonder",
  "laugh",
  "thousand",
  "ago",
  "ran",
  "check",
  "game",
  "shape",
  "equate",
  "hot",
  "miss",
  "brought",
  "heat",
  "snow",
  "tire",
  "bring",
  "yes",
  "distant",
  "fill",
  "east",
  "paint",
  "language",
  "among",
  "grand",
  "ball",
  "yet",
  "wave",
  "drop",
  "heart",
  "am",
  "present",
  "heavy",
  "dance",
  "engine",
  "position",
  "arm",
  "wide",
  "sail",
  "material",
  "size",
  "vary",
  "settle",
  "speak",
  "weight",
  "general",
  "ice",
  "matter",
  "circle",
  "pair",
  "include",
  "divide",
  "syllable",
  "felt",
  "perhaps",
  "pick",
  "sudden",
  "count",
  "square",
  "reason",
  "length",
  "represent",
  "art",
  "subject",
  "region",
  "energy",
  "hunt",
  "probable",
  "bed",
  "brother",
  "egg",
  "ride",
  "cell",
  "believe",
  "fraction",
  "forest",
  "sit",
  "race",
  "window",
  "store",
  "summer",
  "train",
  "sleep",
  "prove",
  "lone",
  "leg",
  "exercise",
  "wall",
  "catch",
  "mount",
  "wish",
  "sky",
  "board",
  "joy",
  "winter",
  "sat",
  "written",
  "wild",
  "instrument",
  "kept",
  "glass",
  "grass",
  "cow",
  "job",
  "edge",
  "sign",
  "visit",
  "past",
  "soft",
  "fun",
  "bright",
  "gas",
  "weather",
  "month",
  "million",
  "bear",
  "finish",
  "happy",
  "hope",
  "flower",
  "clothe",
  "strange",
  "gone",
  "jump",
  "baby",
  "eight",
  "village",
  "meet",
  "root",
  "buy",
  "raise",
  "solve",
  "metal",
  "whether",
  "push",
  "seven",
  "paragraph",
  "third",
  "shall",
  "held",
  "hair",
  "describe",
  "cook",
  "floor",
  "either",
  "result",
  "burn",
  "hill",
  "safe",
  "cat",
  "century",
  "consider",
  "type",
  "law",
  "bit",
  "coast",
  "copy",
  "phrase",
  "silent",
  "tall",
  "sand",
  "soil",
  "roll",
  "temperature",
  "finger",
  "industry",
  "value",
  "fight",
  "lie",
  "beat",
  "excite",
  "natural",
  "view",
  "sense",
  "ear",
  "else",
  "quite",
  "broke",
  "case",
  "middle",
  "kill",
  "son",
  "lake",
  "moment",
  "scale",
  "loud",
  "spring",
  "observe",
  "child",
  "straight",
  "consonant",
  "nation",
  "dictionary",
  "milk",
  "speed",
  "method",
  "organ",
  "pay",
  "age",
  "section",
  "dress",
  "cloud",
  "surprise",
  "quiet",
  "stone",
  "tiny",
  "climb",
  "cool",
  "design",
  "poor",
  "lot",
  "experiment",
  "bottom",
  "key",
  "iron",
  "single",
  "stick",
  "flat",
  "twenty",
  "skin",
  "smile",
  "crease",
  "hole",
  "trade",
  "melody",
  "trip",
  "office",
  "receive",
  "row",
  "mouth",
  "exact",
  "symbol",
  "die",
  "least",
  "trouble",
  "shout",
  "except",
  "wrote",
  "seed",
  "tone",
  "join",
  "suggest",
  "clean",
  "break",
  "lady",
  "yard",
  "rise",
  "bad",
  "blow",
  "oil",
  "blood",
  "touch",
  "grew",
  "cent",
  "mix",
  "team",
  "wire",
  "cost",
  "lost",
  "brown",
  "wear",
  "garden",
  "equal",
  "sent",
  "choose",
  "fell",
  "fit",
  "flow",
  "fair",
  "bank",
  "collect",
  "save",
  "control",
  "decimal",
  "gentle",
  "woman",
  "captain",
  "practice",
  "separate",
  "difficult",
  "doctor",
  "please",
  "protect",
  "noon",
  "whose",
  "locate",
  "ring",
  "character",
  "insect",
  "caught",
  "period",
  "indicate",
  "radio",
  "spoke",
  "atom",
  "human",
  "history",
  "effect",
  "electric",
  "expect",
  "crop",
  "modern",
  "element",
  "hit",
  "student",
  "corner",
  "party",
  "supply",
  "bone",
  "rail",
  "imagine",
  "provide",
  "agree",
  "thus",
  "capital",
  "won't",
  "chair",
  "danger",
  "fruit",
  "rich",
  "thick",
  "soldier",
  "process",
  "operate",
  "guess",
  "necessary",
  "sharp",
  "wing",
  "create",
  "neighbor",
  "wash",
  "bat",
  "rather",
  "crowd",
  "corn",
  "compare",
  "poem",
  "string",
  "bell",
  "depend",
  "meat",
  "rub",
  "tube",
  "famous",
  "dollar",
  "stream",
  "fear",
  "sight",
  "thin",
  "triangle",
  "planet",
  "hurry",
  "chief",
  "colony",
  "clock",
  "mine",
  "tie",
  "enter",
  "major",
  "fresh",
  "search",
  "send",
  "yellow",
  "gun",
  "allow",
  "print",
  "dead",
  "spot",
  "desert",
  "suit",
  "current",
  "lift",
  "rose",
  "continue",
  "block",
  "chart",
  "hat",
  "sell",
  "success",
  "company",
  "subtract",
  "event",
  "particular",
  "deal",
  "swim",
  "term",
  "opposite",
  "wife",
  "shoe",
  "shoulder",
  "spread",
  "arrange",
  "camp",
  "invent",
  "cotton",
  "born",
  "determine",
  "quart",
  "nine",
  "truck",
  "noise",
  "level",
  "chance",
  "gather",
  "shop",
  "stretch",
  "throw",
  "shine",
  "property",
  "column",
  "molecule",
  "select",
  "wrong",
  "gray",
  "repeat",
  "require",
  "broad",
  "prepare",
  "salt",
  "nose",
  "plural",
  "anger",
  "claim",
  "continent",
  "oxygen",
  "sugar",
  "death",
  "pretty",
  "skill",
  "women",
  "season",
  "solution",
  "magnet",
  "silver",
  "thank",
  "branch",
  "match",
  "suffix",
  "especially",
  "fig",
  "afraid",
  "huge",
  "sister",
  "steel",
  "discuss",
  "forward",
  "similar",
  "guide",
  "experience",
  "score",
  "apple",
  "bought",
  "led",
  "pitch",
  "coat",
  "mass",
  "card",
  "band",
  "rope",
  "slip",
  "win",
  "dream",
  "evening",
  "condition",
  "feed",
  "tool",
  "total",
  "basic",
  "smell",
  "valley",
  "nor",
  "double",
  "seat",
  "arrive",
  "master",
  "track",
  "parent",
  "shore",
  "division",
  "sheet",
  "substance",
  "favor",
  "connect",
  "post",
  "spend",
  "chord",
  "fat",
  "glad",
  "original",
  "share",
  "station",
  "dad",
  "bread",
  "charge",
  "proper",
  "bar",
  "offer",
  "segment",
  "slave",
  "duck",
  "instant",
  "market",
  "degree",
  "populate",
  "chick",
  "dear",
  "enemy",
  "reply",
  "drink",
  "occur",
  "support",
  "speech",
  "nature",
  "range",
  "steam",
  "motion",
  "path",
  "liquid",
  "log",
  "meant",
  "quotient",
  "teeth",
  "shell",
  "neck"
];

export function generateRandomWords() {
  const shuffled = words
    .map((value) => ({ value, sort: Math.random() }))
    .sort((a, b) => a.sort - b.sort)
    .map(({ value }) => value);

  return shuffled.join(" ");
}
